### ISSUE TITLE
Set HTTP `User-Agent` header for `isomorphic-unfetch`

### ISSUE THREAD

**Issue by merkys** [tilde-lab/optimade-client#12]
It is usually very nice when software presents itself in the HTTP `User-Agent` header. Web browsers almost always present themselves in a verbose but neat way. This way the server-side developers are informed about what software makes requests to their servers, and may occasionally forward common issues to the client developers. Moreover, usage statistics could be drawn at the server-size, which is nice.

optimade-client seems to be using JS `isomorphic-unfetch` package for HTTP requests. By default its `User-Agent` is `node-fetch/<version> (+https://github.com/bitinn/node-fetch)`. Changing this should not be difficult. It would be nice to see `tilde-lab-optimade-client/<version>` (or something similar) at least.

If user privacy is concern, it should be kept in mind that this is F/LOSS, thus anyone concerned with their privacy are free to patch their copy of the client to their liking.

**Comment by Valexr** [comment]
> @Valexr please could you have a look?

Ok, will see 🤓

**Comment by merkys** [comment]
Great, thanks!
