### ISSUE TITLE
Introduce AbortController for the fetch timeout

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/optimade-client#3]
Currently the requests are not aborted via the timeout, this should be achieved with the [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController).

**Comment by PaulMaly** [comment]
Implemented with this [commit](https://github.com/tilde-lab/optimade-client/commit/e34448a6d7dd360dff3795557e4119e1d91b641e)
